apiVersion: v1
kind: Service
metadata:
  name: template-openapi
  labels:
    application: template-openapi
spec:
  type: LoadBalancer
  selector:
    application: template-openapi
  ports:
  - name: template-openapi
    port: 8087
    targetPort: 8087
    protocol: TCP
